---
title: "test assignment"
author: Paulina STapor (i6325887)
output: html_document
---

```{r}

library(readr)
Covid_cleaned <- read_csv("open_covid_data/Covid_cleaned.csv")
if (interactive()) View(Covid_cleaned)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(ggplot2)
library(slider)
library(scales)

library(ggplot2)
library(dplyr)
```

Date: `r Sys.Date()`


```{r dataset, include = FALSE}
smaller <- diamonds %>% 
  filter(carat <= 2.5)
```

We have  data about `r nrow(diamonds)` diamonds. Only `r nrow(diamonds) - nrow(smaller)` are larger than
2.5 carats. The distribution of the remainder is shown below:

## Including Plots

You can also embed plots, for example:

```{r, echo = FALSE}
continent_daily <- Covid_cleaned %>%
     mutate(
     est_new_cases = (new_cases_per_million / 1e6) * population
   ) %>%
     group_by(continent, date) %>%
     summarise(
         new_cases = sum(est_new_cases, na.rm = TRUE),
         pop = sum(population, na.rm = TRUE),
         .groups = "drop"
     ) %>%
     mutate(
         new_cases_per_million_cont = (new_cases / pop) * 1e6
     )
continent_daily <- continent_daily %>%
    group_by(continent) %>%
     arrange(continent, date) %>%
     mutate(
         new_cases_pm_7dma = slider::slide_dbl(
             new_cases_per_million_cont,
             mean,
             .before = 6, .complete = TRUE, na.rm = TRUE
         )
     ) %>%
     ungroup()

```

```{r}
library(readr)
Covid_cleaned <- read_csv("open_covid_data/Covid_cleaned.csv")
ggplot(continent_daily, aes(x = date, y = new_cases_pm_7dma, color = continent)) +
     geom_line(linewidth = 1.1, alpha = 0.95) +
     scale_x_date(date_breaks = "6 months", date_labels = "%b\n%Y") +
     scale_y_continuous(labels = scales::label_number(accuracy = 1)) +
     labs(
         title = "COVID-19 New Cases per Million (7-day moving average)",
         subtitle = "Countries pooled to continent level (population-weighted)",
         x = "Date",
         y = "New cases per million (7DMA)",
         color = "Continent"
     ) +
     theme_minimal(base_size = 14) +
     theme(
         plot.title = element_text(face = "bold", size = 20),
         plot.subtitle = element_text(size = 13),
         legend.position = "bottom",
         panel.grid.minor = element_blank()
    )

```