# =========================================================
# Install + Load Packages (robust)
# =========================================================
required_packages <- c("readr", "here", "skimr", "DataExplorer")

for (pkg in required_packages) {
  
  # ---- Install if missing (robust check)
  if (!requireNamespace(pkg, quietly = TRUE)) {
    install.packages(pkg, dependencies = TRUE)
  }
  
  # ---- Load (safe even if pkg is a variable)
  suppressPackageStartupMessages(
    library(pkg, character.only = TRUE)
  )
}

# =========================================================
# Read the Dataset
# =========================================================
df <- readr::read_csv(
  here::here("open_covid_data", "Covid_cleaned.csv"),
  show_col_types = FALSE
)

# =========================================================
# Comprehensive Summary (Console)
# =========================================================
skim(df)
# =========================================================
# Full Automated EDA Report (HTML Output)
# =========================================================
create_report(
  df,
  output_dir = here(),
  output_file = "20260227_Preliminary_EDA_Autogenerated_by_DataExplorer.html",
  report_title = "Preliminary Autogenerated Data Exploration (DataExplorer R Package)"
)